# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\lcmap\TSTools-master\tstools\ui\ui_controls.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Controls(object):
    def setupUi(self, Controls):
        Controls.setObjectName(_fromUtf8("Controls"))
        Controls.resize(320, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Controls.sizePolicy().hasHeightForWidth())
        Controls.setSizePolicy(sizePolicy)
        Controls.setMinimumSize(QtCore.QSize(320, 480))
        self.verticalLayout_2 = QtGui.QVBoxLayout(Controls)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_options = QtGui.QWidget()
        self.tab_options.setObjectName(_fromUtf8("tab_options"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_options)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab_options, _fromUtf8(""))
        self.tab_symbology = QtGui.QWidget()
        self.tab_symbology.setObjectName(_fromUtf8("tab_symbology"))
        self.gridLayout = QtGui.QGridLayout(self.tab_symbology)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.combox_symbology_series = QtGui.QComboBox(self.tab_symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_symbology_series.sizePolicy().hasHeightForWidth())
        self.combox_symbology_series.setSizePolicy(sizePolicy)
        self.combox_symbology_series.setObjectName(_fromUtf8("combox_symbology_series"))
        self.gridLayout.addWidget(self.combox_symbology_series, 2, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.tab_symbology)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.stacked_symbology = QtGui.QStackedWidget(self.tab_symbology)
        self.stacked_symbology.setObjectName(_fromUtf8("stacked_symbology"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stacked_symbology.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stacked_symbology.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stacked_symbology, 4, 0, 1, 3)
        self.but_symbol_apply = QtGui.QPushButton(self.tab_symbology)
        self.but_symbol_apply.setObjectName(_fromUtf8("but_symbol_apply"))
        self.gridLayout.addWidget(self.but_symbol_apply, 10, 0, 1, 3)
        self.line_6 = QtGui.QFrame(self.tab_symbology)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 8, 0, 1, 3)
        self.cbox_symbolcontrol = QtGui.QCheckBox(self.tab_symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_symbolcontrol.sizePolicy().hasHeightForWidth())
        self.cbox_symbolcontrol.setSizePolicy(sizePolicy)
        self.cbox_symbolcontrol.setObjectName(_fromUtf8("cbox_symbolcontrol"))
        self.gridLayout.addWidget(self.cbox_symbolcontrol, 0, 0, 1, 3)
        self.line_4 = QtGui.QFrame(self.tab_symbology)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 3)
        self.line = QtGui.QFrame(self.tab_symbology)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 3)
        self.tabWidget.addTab(self.tab_symbology, _fromUtf8(""))
        self.tab_images = QtGui.QWidget()
        self.tab_images.setObjectName(_fromUtf8("tab_images"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_images)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.tab_images)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.combox_table_series = QtGui.QComboBox(self.tab_images)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_table_series.sizePolicy().hasHeightForWidth())
        self.combox_table_series.setSizePolicy(sizePolicy)
        self.combox_table_series.setObjectName(_fromUtf8("combox_table_series"))
        self.gridLayout_2.addWidget(self.combox_table_series, 0, 1, 1, 2)
        self.line_5 = QtGui.QFrame(self.tab_images)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 1, 0, 1, 3)
        self.stacked_table = QtGui.QStackedWidget(self.tab_images)
        self.stacked_table.setObjectName(_fromUtf8("stacked_table"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.stacked_table.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.stacked_table.addWidget(self.page_4)
        self.gridLayout_2.addWidget(self.stacked_table, 2, 0, 1, 3)
        self.tabWidget.addTab(self.tab_images, _fromUtf8(""))
        self.tab_plot = QtGui.QWidget()
        self.tab_plot.setObjectName(_fromUtf8("tab_plot"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_plot)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab_plot)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 17, 0, 1, 4)
        self.cbox_xscale_fix = QtGui.QCheckBox(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_xscale_fix.sizePolicy().hasHeightForWidth())
        self.cbox_xscale_fix.setSizePolicy(sizePolicy)
        self.cbox_xscale_fix.setObjectName(_fromUtf8("cbox_xscale_fix"))
        self.gridLayout_3.addWidget(self.cbox_xscale_fix, 20, 0, 1, 4)
        self.rad_axis_1 = QtGui.QRadioButton(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rad_axis_1.sizePolicy().hasHeightForWidth())
        self.rad_axis_1.setSizePolicy(sizePolicy)
        self.rad_axis_1.setObjectName(_fromUtf8("rad_axis_1"))
        self.gridLayout_3.addWidget(self.rad_axis_1, 9, 0, 1, 2)
        self.lab_min = QtGui.QLabel(self.tab_plot)
        self.lab_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_min.setObjectName(_fromUtf8("lab_min"))
        self.gridLayout_3.addWidget(self.lab_min, 13, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 4)
        self.edit_ymax = QtGui.QLineEdit(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ymax.sizePolicy().hasHeightForWidth())
        self.edit_ymax.setSizePolicy(sizePolicy)
        self.edit_ymax.setInputMask(_fromUtf8(""))
        self.edit_ymax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_ymax.setObjectName(_fromUtf8("edit_ymax"))
        self.gridLayout_3.addWidget(self.edit_ymax, 14, 1, 1, 3)
        self.edit_ymin = QtGui.QLineEdit(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ymin.sizePolicy().hasHeightForWidth())
        self.edit_ymin.setSizePolicy(sizePolicy)
        self.edit_ymin.setInputMask(_fromUtf8(""))
        self.edit_ymin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_ymin.setObjectName(_fromUtf8("edit_ymin"))
        self.gridLayout_3.addWidget(self.edit_ymin, 13, 1, 1, 3)
        self.lab_band = QtGui.QLabel(self.tab_plot)
        self.lab_band.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_band.setObjectName(_fromUtf8("lab_band"))
        self.gridLayout_3.addWidget(self.lab_band, 6, 0, 1, 1)
        self.combox_band = QtGui.QComboBox(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_band.sizePolicy().hasHeightForWidth())
        self.combox_band.setSizePolicy(sizePolicy)
        self.combox_band.setObjectName(_fromUtf8("combox_band"))
        self.gridLayout_3.addWidget(self.combox_band, 6, 1, 1, 3)
        self.but_symbology = QtGui.QPushButton(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_symbology.sizePolicy().hasHeightForWidth())
        self.but_symbology.setSizePolicy(sizePolicy)
        self.but_symbology.setObjectName(_fromUtf8("but_symbology"))
        self.gridLayout_3.addWidget(self.but_symbology, 27, 0, 1, 4)
        self.label_3 = QtGui.QLabel(self.tab_plot)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 7, 0, 1, 4)
        self.lab_max = QtGui.QLabel(self.tab_plot)
        self.lab_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_max.setObjectName(_fromUtf8("lab_max"))
        self.gridLayout_3.addWidget(self.lab_max, 14, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.tab_plot)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_3.addWidget(self.line_7, 1, 0, 1, 4)
        self.cbox_yscale_auto = QtGui.QCheckBox(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_yscale_auto.sizePolicy().hasHeightForWidth())
        self.cbox_yscale_auto.setSizePolicy(sizePolicy)
        self.cbox_yscale_auto.setObjectName(_fromUtf8("cbox_yscale_auto"))
        self.gridLayout_3.addWidget(self.cbox_yscale_auto, 10, 0, 1, 4)
        self.rad_axis_2 = QtGui.QRadioButton(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rad_axis_2.sizePolicy().hasHeightForWidth())
        self.rad_axis_2.setSizePolicy(sizePolicy)
        self.rad_axis_2.setObjectName(_fromUtf8("rad_axis_2"))
        self.gridLayout_3.addWidget(self.rad_axis_2, 9, 2, 1, 2)
        self.cbox_plotlayer = QtGui.QCheckBox(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_plotlayer.sizePolicy().hasHeightForWidth())
        self.cbox_plotlayer.setSizePolicy(sizePolicy)
        self.cbox_plotlayer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbox_plotlayer.setObjectName(_fromUtf8("cbox_plotlayer"))
        self.gridLayout_3.addWidget(self.cbox_plotlayer, 0, 0, 1, 4)
        self.lab_xmin = QtGui.QLabel(self.tab_plot)
        self.lab_xmin.setMinimumSize(QtCore.QSize(40, 0))
        self.lab_xmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_xmin.setObjectName(_fromUtf8("lab_xmin"))
        self.gridLayout_3.addWidget(self.lab_xmin, 18, 0, 1, 1)
        self.scroll_xmin = QtGui.QScrollBar(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_xmin.sizePolicy().hasHeightForWidth())
        self.scroll_xmin.setSizePolicy(sizePolicy)
        self.scroll_xmin.setPageStep(1)
        self.scroll_xmin.setTracking(False)
        self.scroll_xmin.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_xmin.setObjectName(_fromUtf8("scroll_xmin"))
        self.gridLayout_3.addWidget(self.scroll_xmin, 18, 1, 1, 3)
        self.lab_xmax = QtGui.QLabel(self.tab_plot)
        self.lab_xmax.setMinimumSize(QtCore.QSize(40, 0))
        self.lab_xmax.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_xmax.setObjectName(_fromUtf8("lab_xmax"))
        self.gridLayout_3.addWidget(self.lab_xmax, 19, 0, 1, 1)
        self.scroll_xmax = QtGui.QScrollBar(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_xmax.sizePolicy().hasHeightForWidth())
        self.scroll_xmax.setSizePolicy(sizePolicy)
        self.scroll_xmax.setPageStep(1)
        self.scroll_xmax.setProperty("value", 99)
        self.scroll_xmax.setSliderPosition(99)
        self.scroll_xmax.setTracking(False)
        self.scroll_xmax.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_xmax.setObjectName(_fromUtf8("scroll_xmax"))
        self.gridLayout_3.addWidget(self.scroll_xmax, 19, 1, 1, 3)
        self.label_2 = QtGui.QLabel(self.tab_plot)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 21, 0, 1, 4)
        self.edit_maskvalues = QtGui.QLineEdit(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_maskvalues.sizePolicy().hasHeightForWidth())
        self.edit_maskvalues.setSizePolicy(sizePolicy)
        self.edit_maskvalues.setText(_fromUtf8(""))
        self.edit_maskvalues.setObjectName(_fromUtf8("edit_maskvalues"))
        self.gridLayout_3.addWidget(self.edit_maskvalues, 23, 2, 1, 2)
        self.cbox_fmask = QtGui.QCheckBox(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_fmask.sizePolicy().hasHeightForWidth())
        self.cbox_fmask.setSizePolicy(sizePolicy)
        self.cbox_fmask.setObjectName(_fromUtf8("cbox_fmask"))
        self.gridLayout_3.addWidget(self.cbox_fmask, 23, 0, 1, 2)
        self.cbox_modelfit = QtGui.QCheckBox(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_modelfit.sizePolicy().hasHeightForWidth())
        self.cbox_modelfit.setSizePolicy(sizePolicy)
        self.cbox_modelfit.setObjectName(_fromUtf8("cbox_modelfit"))
        self.gridLayout_3.addWidget(self.cbox_modelfit, 24, 0, 1, 2)
        self.cbox_breakpoint = QtGui.QCheckBox(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_breakpoint.sizePolicy().hasHeightForWidth())
        self.cbox_breakpoint.setSizePolicy(sizePolicy)
        self.cbox_breakpoint.setObjectName(_fromUtf8("cbox_breakpoint"))
        self.gridLayout_3.addWidget(self.cbox_breakpoint, 24, 2, 1, 2)
        self.line_2 = QtGui.QFrame(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 26, 0, 1, 4)
        self.cbox_custom = QtGui.QCheckBox(self.tab_plot)
        self.cbox_custom.setObjectName(_fromUtf8("cbox_custom"))
        self.gridLayout_3.addWidget(self.cbox_custom, 25, 0, 1, 2)
        self.tabWidget.addTab(self.tab_plot, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Controls)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Controls)
        Controls.setTabOrder(self.tabWidget, self.cbox_plotlayer)
        Controls.setTabOrder(self.cbox_plotlayer, self.combox_band)
        Controls.setTabOrder(self.combox_band, self.rad_axis_1)
        Controls.setTabOrder(self.rad_axis_1, self.rad_axis_2)
        Controls.setTabOrder(self.rad_axis_2, self.cbox_yscale_auto)
        Controls.setTabOrder(self.cbox_yscale_auto, self.edit_ymin)
        Controls.setTabOrder(self.edit_ymin, self.edit_ymax)
        Controls.setTabOrder(self.edit_ymax, self.cbox_xscale_fix)
        Controls.setTabOrder(self.cbox_xscale_fix, self.cbox_fmask)
        Controls.setTabOrder(self.cbox_fmask, self.cbox_modelfit)
        Controls.setTabOrder(self.cbox_modelfit, self.cbox_breakpoint)
        Controls.setTabOrder(self.cbox_breakpoint, self.edit_maskvalues)
        Controls.setTabOrder(self.edit_maskvalues, self.but_symbology)
        Controls.setTabOrder(self.but_symbology, self.combox_table_series)
        Controls.setTabOrder(self.combox_table_series, self.cbox_symbolcontrol)
        Controls.setTabOrder(self.cbox_symbolcontrol, self.combox_symbology_series)
        Controls.setTabOrder(self.combox_symbology_series, self.but_symbol_apply)

    def retranslateUi(self, Controls):
        Controls.setWindowTitle(_translate("Controls", "Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_options), _translate("Controls", "Options", None))
        self.label_5.setText(_translate("Controls", "Series", None))
        self.but_symbol_apply.setText(_translate("Controls", "Apply", None))
        self.cbox_symbolcontrol.setText(_translate("Controls", "Control time series image symbology", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_symbology), _translate("Controls", "Symbology", None))
        self.label_7.setText(_translate("Controls", "Series", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_images), _translate("Controls", "Images", None))
        self.label_4.setText(_translate("Controls", "<html><head/><body><p><span style=\" font-weight:600;\">Date Range</span></p></body></html>", None))
        self.cbox_xscale_fix.setText(_translate("Controls", "Fixed date range", None))
        self.rad_axis_1.setText(_translate("Controls", "Axis 1", None))
        self.lab_min.setText(_translate("Controls", "Min", None))
        self.label.setText(_translate("Controls", "<html><head/><body><p><span style=\" font-weight:600;\">Band Options</span></p></body></html>", None))
        self.edit_ymax.setText(_translate("Controls", "0", None))
        self.edit_ymin.setText(_translate("Controls", "10000", None))
        self.lab_band.setText(_translate("Controls", "Band", None))
        self.but_symbology.setText(_translate("Controls", "Symbology", None))
        self.label_3.setText(_translate("Controls", "<html><head/><body><p><span style=\" font-weight:600;\">Y-Axis</span></p></body></html>", None))
        self.lab_max.setText(_translate("Controls", "Max", None))
        self.cbox_yscale_auto.setText(_translate("Controls", "Auto-scale", None))
        self.rad_axis_2.setText(_translate("Controls", "Axis 2", None))
        self.cbox_plotlayer.setText(_translate("Controls", "Click to Add Points from Plot", None))
        self.lab_xmin.setText(_translate("Controls", "Start", None))
        self.lab_xmax.setText(_translate("Controls", "End", None))
        self.label_2.setText(_translate("Controls", "<html><head/><body><p><span style=\" font-weight:600;\">Plot Features</span></p></body></html>", None))
        self.cbox_fmask.setText(_translate("Controls", "Fmask", None))
        self.cbox_modelfit.setText(_translate("Controls", "Model Fit", None))
        self.cbox_breakpoint.setText(_translate("Controls", "Break Points", None))
        self.cbox_custom.setText(_translate("Controls", "Driver specific", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plot), _translate("Controls", "Plot", None))

