# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\lcmap\TSTools-master\tstools\ui\ui_raster_symbology.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Raster_Symbology(object):
    def setupUi(self, Raster_Symbology):
        Raster_Symbology.setObjectName(_fromUtf8("Raster_Symbology"))
        Raster_Symbology.resize(306, 423)
        self.gridLayout = QtGui.QGridLayout(Raster_Symbology)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lab_colorstretch = QtGui.QLabel(Raster_Symbology)
        self.lab_colorstretch.setTextFormat(QtCore.Qt.AutoText)
        self.lab_colorstretch.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_colorstretch.setObjectName(_fromUtf8("lab_colorstretch"))
        self.gridLayout.addWidget(self.lab_colorstretch, 5, 0, 1, 3)
        self.lab_bandselect = QtGui.QLabel(Raster_Symbology)
        self.lab_bandselect.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_bandselect.setObjectName(_fromUtf8("lab_bandselect"))
        self.gridLayout.addWidget(self.lab_bandselect, 1, 0, 1, 3)
        self.lab_green = QtGui.QLabel(Raster_Symbology)
        self.lab_green.setObjectName(_fromUtf8("lab_green"))
        self.gridLayout.addWidget(self.lab_green, 3, 0, 1, 1)
        self.combox_red = QtGui.QComboBox(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_red.sizePolicy().hasHeightForWidth())
        self.combox_red.setSizePolicy(sizePolicy)
        self.combox_red.setObjectName(_fromUtf8("combox_red"))
        self.gridLayout.addWidget(self.combox_red, 2, 1, 1, 2)
        self.lab_blue = QtGui.QLabel(Raster_Symbology)
        self.lab_blue.setObjectName(_fromUtf8("lab_blue"))
        self.gridLayout.addWidget(self.lab_blue, 4, 0, 1, 1)
        self.lab_symbol_max = QtGui.QLabel(Raster_Symbology)
        self.lab_symbol_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_symbol_max.setObjectName(_fromUtf8("lab_symbol_max"))
        self.gridLayout.addWidget(self.lab_symbol_max, 6, 2, 1, 1)
        self.combox_green = QtGui.QComboBox(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_green.sizePolicy().hasHeightForWidth())
        self.combox_green.setSizePolicy(sizePolicy)
        self.combox_green.setObjectName(_fromUtf8("combox_green"))
        self.gridLayout.addWidget(self.combox_green, 3, 1, 1, 2)
        self.label_7 = QtGui.QLabel(Raster_Symbology)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.lab_symbol_min = QtGui.QLabel(Raster_Symbology)
        self.lab_symbol_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_symbol_min.setObjectName(_fromUtf8("lab_symbol_min"))
        self.gridLayout.addWidget(self.lab_symbol_min, 6, 1, 1, 1)
        self.lab_cenhance = QtGui.QLabel(Raster_Symbology)
        self.lab_cenhance.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_cenhance.setObjectName(_fromUtf8("lab_cenhance"))
        self.gridLayout.addWidget(self.lab_cenhance, 10, 0, 1, 3)
        self.edit_redmin = QtGui.QLineEdit(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_redmin.sizePolicy().hasHeightForWidth())
        self.edit_redmin.setSizePolicy(sizePolicy)
        self.edit_redmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_redmin.setObjectName(_fromUtf8("edit_redmin"))
        self.gridLayout.addWidget(self.edit_redmin, 7, 1, 1, 1)
        self.combox_cenhance = QtGui.QComboBox(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_cenhance.sizePolicy().hasHeightForWidth())
        self.combox_cenhance.setSizePolicy(sizePolicy)
        self.combox_cenhance.setObjectName(_fromUtf8("combox_cenhance"))
        self.combox_cenhance.addItem(_fromUtf8(""))
        self.combox_cenhance.addItem(_fromUtf8(""))
        self.combox_cenhance.addItem(_fromUtf8(""))
        self.combox_cenhance.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.combox_cenhance, 11, 0, 1, 3)
        self.combox_blue = QtGui.QComboBox(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_blue.sizePolicy().hasHeightForWidth())
        self.combox_blue.setSizePolicy(sizePolicy)
        self.combox_blue.setObjectName(_fromUtf8("combox_blue"))
        self.gridLayout.addWidget(self.combox_blue, 4, 1, 1, 2)
        self.edit_redmax = QtGui.QLineEdit(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_redmax.sizePolicy().hasHeightForWidth())
        self.edit_redmax.setSizePolicy(sizePolicy)
        self.edit_redmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_redmax.setObjectName(_fromUtf8("edit_redmax"))
        self.gridLayout.addWidget(self.edit_redmax, 7, 2, 1, 1)
        self.label_8 = QtGui.QLabel(Raster_Symbology)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.lab_red = QtGui.QLabel(Raster_Symbology)
        self.lab_red.setObjectName(_fromUtf8("lab_red"))
        self.gridLayout.addWidget(self.lab_red, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Raster_Symbology)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.edit_greenmin = QtGui.QLineEdit(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_greenmin.sizePolicy().hasHeightForWidth())
        self.edit_greenmin.setSizePolicy(sizePolicy)
        self.edit_greenmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_greenmin.setObjectName(_fromUtf8("edit_greenmin"))
        self.gridLayout.addWidget(self.edit_greenmin, 8, 1, 1, 1)
        self.edit_greenmax = QtGui.QLineEdit(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_greenmax.sizePolicy().hasHeightForWidth())
        self.edit_greenmax.setSizePolicy(sizePolicy)
        self.edit_greenmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_greenmax.setObjectName(_fromUtf8("edit_greenmax"))
        self.gridLayout.addWidget(self.edit_greenmax, 8, 2, 1, 1)
        self.edit_bluemin = QtGui.QLineEdit(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_bluemin.sizePolicy().hasHeightForWidth())
        self.edit_bluemin.setSizePolicy(sizePolicy)
        self.edit_bluemin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_bluemin.setObjectName(_fromUtf8("edit_bluemin"))
        self.gridLayout.addWidget(self.edit_bluemin, 9, 1, 1, 1)
        self.edit_bluemax = QtGui.QLineEdit(Raster_Symbology)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_bluemax.sizePolicy().hasHeightForWidth())
        self.edit_bluemax.setSizePolicy(sizePolicy)
        self.edit_bluemax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_bluemax.setObjectName(_fromUtf8("edit_bluemax"))
        self.gridLayout.addWidget(self.edit_bluemax, 9, 2, 1, 1)

        self.retranslateUi(Raster_Symbology)
        QtCore.QMetaObject.connectSlotsByName(Raster_Symbology)
        Raster_Symbology.setTabOrder(self.combox_red, self.combox_green)
        Raster_Symbology.setTabOrder(self.combox_green, self.combox_blue)
        Raster_Symbology.setTabOrder(self.combox_blue, self.edit_redmin)
        Raster_Symbology.setTabOrder(self.edit_redmin, self.edit_redmax)
        Raster_Symbology.setTabOrder(self.edit_redmax, self.edit_greenmin)
        Raster_Symbology.setTabOrder(self.edit_greenmin, self.edit_greenmax)
        Raster_Symbology.setTabOrder(self.edit_greenmax, self.edit_bluemin)
        Raster_Symbology.setTabOrder(self.edit_bluemin, self.edit_bluemax)
        Raster_Symbology.setTabOrder(self.edit_bluemax, self.combox_cenhance)

    def retranslateUi(self, Raster_Symbology):
        Raster_Symbology.setWindowTitle(_translate("Raster_Symbology", "Form", None))
        self.lab_colorstretch.setText(_translate("Raster_Symbology", "<html><head/><body><p><span style=\" font-weight:600;\">Color Stretch</span></p></body></html>", None))
        self.lab_bandselect.setText(_translate("Raster_Symbology", "<html><head/><body><p><span style=\" font-weight:600;\">Band Selection</span></p></body></html>", None))
        self.lab_green.setText(_translate("Raster_Symbology", "Green", None))
        self.lab_blue.setText(_translate("Raster_Symbology", "Blue", None))
        self.lab_symbol_max.setText(_translate("Raster_Symbology", "Max", None))
        self.label_7.setText(_translate("Raster_Symbology", "Red", None))
        self.lab_symbol_min.setText(_translate("Raster_Symbology", "Min", None))
        self.lab_cenhance.setText(_translate("Raster_Symbology", "<html><head/><body><p><span style=\" font-weight:600;\">Contrast Enhancement</span></p></body></html>", None))
        self.edit_redmin.setText(_translate("Raster_Symbology", "0", None))
        self.combox_cenhance.setItemText(0, _translate("Raster_Symbology", "No Enhancement", None))
        self.combox_cenhance.setItemText(1, _translate("Raster_Symbology", "Stretch to min/max", None))
        self.combox_cenhance.setItemText(2, _translate("Raster_Symbology", "Stretch and clip to min/max", None))
        self.combox_cenhance.setItemText(3, _translate("Raster_Symbology", "Clip to min/max", None))
        self.edit_redmax.setText(_translate("Raster_Symbology", "10000", None))
        self.label_8.setText(_translate("Raster_Symbology", "Green", None))
        self.lab_red.setText(_translate("Raster_Symbology", "Red", None))
        self.label_9.setText(_translate("Raster_Symbology", "Blue", None))
        self.edit_greenmin.setText(_translate("Raster_Symbology", "0", None))
        self.edit_greenmax.setText(_translate("Raster_Symbology", "10000", None))
        self.edit_bluemin.setText(_translate("Raster_Symbology", "0", None))
        self.edit_bluemax.setText(_translate("Raster_Symbology", "10000", None))

